check_interval: 60

youtube:
  enabled: true
  output_dir: "~/Downloads/youtube"
  quality: "best"
  download_existing: false
  monitor_new: true
  record_live: true
  shorts: false
  playlists: false
  chat: true
  channels:
    - https://www.youtube.com/@WELTVideoTV
twitch:
  enabled: false
  output_dir: "~/Downloads/twitch"
  quality: "best"
  record_live: true
  download_vods: true
  download_clips: true
  chat: true
  channels:
    - asmongold
    - xqc

kick:
  enabled: false
  output_dir: "~/Downloads/kick"
  quality: "best"
  record_live: true
  download_vods: true
  chat: true
  channels:
    - tweanks
